development:
  adapter: postgresql
  encoding: unicode
  database: GidtME_development
  pool: 5
  username: GidtME
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: GidtME_test
  pool: 5
  username: GidtME
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: GidtME_production
  pool: 5
  username: GidtME
  password: